[theme]
base="dark"
primaryColor="#fbbf24"
backgroundColor="#1e293b"
secondaryBackgroundColor="#0f172a"
textColor="#f1f5f9"
font="sans serif"

[browser]
gatherUsageStats=false
toolbarMode="minimal"

[server]
headless=true
